
export const CHANGE_FILTER_VALUE = 'CHANGE_FILTER_VALUE';

export const CHANGE_BOOK_MARK_VEIW = 'CHANGE_BOOK_MARK_VEIW';
export const CHANGE_BOOK_MARK_ROOMS = 'CHANGE_BOOK_MARK_ROOMS';

export const ROOM_IMAGE_CLICK = 'ROOM_IMAGE_CLICK';
export const MODAL_VIEW_CLICK = 'MODAL_VIEW_CLICK';

export const REQUEST_ROOMS_PENDING = 'REQUEST_ROOMS_PENDING';
export const REQUEST_ROOMS_SUCCESS = 'REQUEST_ROOMS_SUCCESS';
export const REQUEST_ROOMS_FAILED = 'REQUEST_ROOMS_FAILED';

export const ADD_BOOK_MARK_ALERT = 'ADD_BOOK_MARK_ALERT';
export const REMOVE_BOOK_MARK_ALERT = 'REMOVE_BOOK_MARK_ALERT';
export const FORCE_REMOVE_BOOK_MARK_ALERT = 'FORCE_REMOVE_BOOK_MARK_ALERT';
export const ADJUST_BOOK_MARK_ALERT = 'ADJUST_BOOK_MARK_ALERT';
export const MOUSE_OVER_BOOK_MARK_ALERT = 'MOUSE_OVER_BOOK_MARK_ALERT';
export const MOUSE_OUT_BOOK_MARK_ALERT = "MOUSE_OUT_BOOK_MARK_ALERT";
export const UPDATE_STATUS_BOOK_MAKR_ALERT = 'UPDATE_STATUS_BOOK_MAKR_ALERT';
