
export const CHANGE_FILTER_VALUE = 'CHANGE_FILTER_VALUE';

export const CHANGE_BOOK_MARK_VEIW = 'CHANGE_BOOK_MARK_VEIW';
export const CHANGE_BOOK_MARK_ROOMS = 'CHANGE_BOOK_MARK_ROOMS';

export const ROOM_IMAGE_CLICK = 'ROOM_IMAGE_CLICK';

export const REQUEST_ROOMS_PENDING = 'REQUEST_ROOMS_PENDING';
export const REQUEST_ROOMS_SUCCESS = 'REQUEST_ROOMS_SUCCESS';
export const REQUEST_ROOMS_FAILED = 'REQUEST_ROOMS_FAILED';

